#!/usr/bin/env bash
# Script that make nginx listen to port 80
# script that restores the default server port

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
