#!/usr/bin/env bash

COUNTER=1
while [ $COUNTER -le 100 ]
do
    if [ $((COUNTER % 3)) -eq 0 ] && [ $((COUNTER % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNTER % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((COUNTER % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    COUNTER=$((COUNTER + 1))
done
